title: "PRBSTAT1B Tutorial Notes"
description: "Information and Notes for PRBSTAT1B Students"
theme: minima
author: Toby Jermy

# Only show these pages in the header navigation
header_pages:
  - index.md

# Markdown rendering
markdown: kramdown
kramdown:
  math_engine: mathjax
